# Generated by Django 5.0.3 on 2024-05-24 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myhotel.basemodel')),
                ('facility_name', models.CharField(max_length=100)),
            ],
            bases=('myhotel.basemodel',),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myhotel.basemodel')),
                ('hotel_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('hotel_price', models.IntegerField()),
                ('facility', models.ManyToManyField(to='myhotel.facility')),
            ],
            bases=('myhotel.basemodel',),
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myhotel.basemodel')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booking_type', models.CharField(choices=[('Pre Paid', 'Pre Paid'), ('Post Paid', 'Post Paid')], max_length=100)),
                ('hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhotel.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('myhotel.basemodel',),
        ),
    ]
